In [ ]:
import pandas as pd
data=pd.read_excel("/content/employeeinfo.xlsx")
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,NaN,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,NaN,10-05-2023
3,NaN,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,01-02-2023
8,E109,NaN,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

info()-shows basic info about the DataFrame(rows,coloums,memory usage)

 dtypes-Tells you the datatype of each column(int,float,object,etc)


**Missing Data**




1. isnull()-Marks missing values as True and others ads False
2. isnull().sum()-Counts missing values in each colums

1. isnull().sum().sum()-count total missing values in whole DataFrame
2. fillna(values)-Fills Missing values with the given value(like 0 or"Unknown").


*   ffill()-Forward fill function
*   bfill()-Backward fill function
*   interpolate()

In [ ]:
data.isnull()

   Employee Id   Name    Age  Gender  Department  Salary   City  joining-date
0        False  False  False   False       False   False  False         False
1        False  False   True   False       False   False  False         False
2        False  False  False   False       False   False   True         False
3         True  False  False   False       False   False  False         False
4        False  False  False   False       False   False  False         False
5        False  False   True   False       False   False  False         False
6        False  False  False   False       False   False  False         False
7        False  False  False    True       False   False  False         False
8        False   True  False   False       False   False  False         False
9        False  False  False   False       False   False  False         False

In [ ]:
data.isnull().sum()

Employee Id     1
Name            1
Age             2
Gender          1
Department      0
Salary          0
City            1
joining-date    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data['City']=data['City'].fillna('Hydrabad')
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,NaN,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,NaN,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,01-02-2023
8,E109,NaN,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data['Age']=data['Age'].fillna(20)
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,NaN,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,01-02-2023
8,E109,NaN,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data['Name']=data['Name'].fillna('Sushila')
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,NaN,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data['Gender']=data['Gender'].fillna('Female')
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,NaN,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee Id   9 non-null      object
 1   Name          10 non-null     object
 2   Age           10 non-null     float64
 3   Gender        10 non-null     object
 4   Department    10 non-null     object
 5   Salary        10 non-null     int64
 6   City          10 non-null     object
 7   joining-date  10 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 772.0+ bytes

In [ ]:
data['Employee Id']=data['Employee Id'].fillna(data["Employee Id"].mode()[0])
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data.isnull().sum()

Employee Id     0
Name            0
Age             0
Gender          0
Department      0
Salary          0
City            0
joining-date    0
dtype: int64

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data['Name']=data['Name'].str.strip()
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data['Department']=data['Department'].str.strip()
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data['City']=data['City'].str.strip()
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
df=data.drop_duplicates()
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
df['City']=df['City'].str.strip()
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024

In [ ]:
df.drop('Age',axis=1)

  Employee Id      Name  Gender Department  Salary      City  joining-date
0        E101     akash       M         IT   45000  Begaluru    12-01-2023
1        E102     Megha       F         HR   38000   Chennai    15-02-2022
2        E103      jhon    Male    finance   55000  Hydrabad    10-05-2023
3        E101     Kavya  female         IT   48000    Mysuru    20-03-2023
4        E105  darshini    Male      Sales   25000  Begaluru    10-06-2026
5        E106   Supriya  Female         HR  -38000   Chennai    15-02-2022
6        E107  darshini    male      sales   25000  Begaluru    10-06-2021
7        E108     Sneha  Female         IT   47000     Delhi    01-02-2023
8        E109   Sushila  female    Finance   52000  Hydrabad    22-08-2022
9        E110     Vikas    Male         IT  999999   Chennai    05-01-2024

In [ ]:
import numpy as np
df.loc[df['Salary']>500000,'Salary']=np.nan
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,240.0,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000.0,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,NaN,Chennai,05-01-2024

In [ ]:
import numpy as np
df.loc[df['Age']>50,'Age']=np.nan
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20.0,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,NaN,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20.0,Female,HR,-38000.0,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23.0,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27.0,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,NaN,Chennai,05-01-2024

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.000000,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20.000000,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28.000000,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,18.111111,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26.000000,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20.000000,Female,HR,-38000.0,Chennai,15-02-2022
6,E107,darshini,26.000000,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23.000000,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27.000000,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22.000000,Male,IT,NaN,Chennai,05-01-2024

In [ ]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.000000,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20.000000,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28.000000,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,18.111111,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26.000000,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20.000000,Female,HR,-38000.0,Chennai,15-02-2022
6,E107,darshini,26.000000,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23.000000,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27.000000,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22.000000,Male,IT,45000.0,Chennai,05-01-2024

In [ ]:
import numpy as np
df.loc[df['Salary']<10000,'Salary']=np.nan
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.000000,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20.000000,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28.000000,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,18.111111,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26.000000,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20.000000,Female,HR,NaN,Chennai,15-02-2022
6,E107,darshini,26.000000,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23.000000,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27.000000,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22.000000,Male,IT,45000.0,Chennai,05-01-2024

In [ ]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.000000,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20.000000,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28.000000,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,18.111111,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26.000000,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20.000000,Female,HR,45000.0,Chennai,15-02-2022
6,E107,darshini,26.000000,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23.000000,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27.000000,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22.000000,Male,IT,45000.0,Chennai,05-01-2024

In [ ]:
df.dtypes

Employee Id      object
Name             object
Age             float64
Gender           object
Department       object
Salary          float64
City             object
joining-date     object
dtype: object

In [ ]:
df['Age']=df['Age'].astype(int)
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25,M,IT,45000.0,Begaluru,12-01-2023
1,E102,Megha,20,F,HR,38000.0,Chennai,15-02-2022
2,E103,jhon,28,Male,finance,55000.0,Hydrabad,10-05-2023
3,E101,Kavya,18,female,IT,48000.0,Mysuru,20-03-2023
4,E105,darshini,26,Male,Sales,25000.0,Begaluru,10-06-2026
5,E106,Supriya,20,Female,HR,45000.0,Chennai,15-02-2022
6,E107,darshini,26,male,sales,25000.0,Begaluru,10-06-2021
7,E108,Sneha,23,Female,IT,47000.0,Delhi,01-02-2023
8,E109,Sushila,-27,female,Finance,52000.0,Hydrabad,22-08-2022
9,E110,Vikas,22,Male,IT,45000.0,Chennai,05-01-2024

In [ ]:
df['Salary']=df['Salary'].astype(int)
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,18,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20,Female,HR,45000,Chennai,15-02-2022
6,E107,darshini,26,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22,Male,IT,45000,Chennai,05-01-2024

In [ ]:
df.dtypes

Employee Id     object
Name            object
Age              int64
Gender          object
Department      object
Salary           int64
City            object
joining-date    object
dtype: object

In [ ]:
df['Gender']=df['Gender'].replace({"M":"Male","F":"Female"})
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25,Male,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20,Female,HR,38000,Chennai,15-02-2022
2,E103,jhon,28,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,18,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20,Female,HR,45000,Chennai,15-02-2022
6,E107,darshini,26,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22,Male,IT,45000,Chennai,05-01-2024

In [ ]:
df['Gender']=df['Gender'].replace({"female":"Female","male":"Male"})
df

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25,Male,IT,45000,Begaluru,12-01-2023
1,E102,Megha,20,Female,HR,38000,Chennai,15-02-2022
2,E103,jhon,28,Male,finance,55000,Hydrabad,10-05-2023
3,E101,Kavya,18,Female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,20,Female,HR,45000,Chennai,15-02-2022
6,E107,darshini,26,Male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23,Female,IT,47000,Delhi,01-02-2023
8,E109,Sushila,-27,Female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22,Male,IT,45000,Chennai,05-01-2024

In [ ]:
df['Name']=df['Name'].replace({"darshini":"Darshi","jhon":"Jhon","akash":"Akash"})
df

  Employee Id     Name  Age  Gender Department  Salary      City  joining-date
0        E101    Akash   25    Male         IT   45000  Begaluru    12-01-2023
1        E102    Megha   20  Female         HR   38000   Chennai    15-02-2022
2        E103     Jhon   28    Male    finance   55000  Hydrabad    10-05-2023
3        E101    Kavya   18  Female         IT   48000    Mysuru    20-03-2023
4        E105   Darshi   26    Male      Sales   25000  Begaluru    10-06-2026
5        E106  Supriya   20  Female         HR   45000   Chennai    15-02-2022
6        E107   Darshi   26    Male      sales   25000  Begaluru    10-06-2021
7        E108    Sneha   23  Female         IT   47000     Delhi    01-02-2023
8        E109  Sushila  -27  Female    Finance   52000  Hydrabad    22-08-2022
9        E110    Vikas   22    Male         IT   45000   Chennai    05-01-2024

In [ ]:
df=pd.get_dummies(df,columns=['Gender'],dtype=int)
df

,Employee Id,Name,Age,Department,Salary,City,joining-date,Gender_Female,Gender_Male
0,E101,Akash,25,IT,45000,Begaluru,12-01-2023,0,1
1,E102,Megha,20,HR,38000,Chennai,15-02-2022,1,0
2,E103,Jhon,28,finance,55000,Hydrabad,10-05-2023,0,1
3,E101,Kavya,18,IT,48000,Mysuru,20-03-2023,1,0
4,E105,Darshi,26,Sales,25000,Begaluru,10-06-2026,0,1
5,E106,Supriya,20,HR,45000,Chennai,15-02-2022,1,0
6,E107,Darshi,26,sales,25000,Begaluru,10-06-2021,0,1
7,E108,Sneha,23,IT,47000,Delhi,01-02-2023,1,0
8,E109,Sushila,-27,Finance,52000,Hydrabad,22-08-2022,1,0
9,E110,Vikas,22,IT,45000,Chennai,05-01-2024,0,1

In [ ]:
import pandas as pd
d=pd.read_excel("/content/Copy of student_data_converted.xlsx")
d

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
10       S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
d.isnull()

    Student ID   Name    Age  Gender  Course  Marks   City  Admission Date
0        False  False  False   False   False  False  False           False
1        False  False   True   False   False  False  False           False
2        False  False  False   False   False  False  False           False
3        False  False  False   False   False  False  False           False
4        False  False  False   False   False  False  False           False
5        False  False  False   False   False  False  False           False
6         True  False  False   False   False  False  False           False
7        False   True  False   False   False  False  False           False
8        False  False  False   False   False  False  False           False
9        False  False  False   False   False  False  False           False
10       False  False  False   False   False  False  False           False
11       False  False  False   False    True  False  False           False
12       False  False  False   False   False   True  False           False
13       False  False  False   False   False  False   True           False
14       False  False  False   False   False  False  False           False

In [ ]:
d.isnull().sum()

Student ID        1
Name              1
Age               1
Gender            0
Course            1
Marks             1
City              1
Admission Date    0
dtype: int64

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student ID      14 non-null     object
 1   Name            14 non-null     object
 2   Age             14 non-null     float64
 3   Gender          15 non-null     object
 4   Course          14 non-null     object
 5   Marks           14 non-null     float64
 6   City            14 non-null     object
 7   Admission Date  15 non-null     object
dtypes: float64(2), object(6)
memory usage: 1.1+ KB

In [ ]:
d.head()

  Student ID   Name    Age  Gender Course  Marks       City Admission Date
0       S201  Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1       S202  Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2       S203  Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3       S204  Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4       S205  Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023

In [ ]:
d.tail()

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
10       S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
d.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
dtype: bool

In [ ]:
d.duplicated().sum()

np.int64(1)

In [ ]:
df=d.drop_duplicates()
df

   Student ID    Name    Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya    NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  150.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22.0    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
import numpy as np
df.loc[df['Age']>25,'Age']=np.nan
df

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   NaN  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   NaN    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi  21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Age']=df['Age'].fillna(20)
df

/tmp/ipykernel_5088/2472978180.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].fillna(20)

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya  20.0  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  20.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi  21.0       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju -19.0       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya  21.0  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen  22.0    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja  20.0  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Age']=df['Age'].astype(int)
df

/tmp/ipykernel_5088/71083683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].astype(int)

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21       M    MCA   95.0      Delhi     01-08-2023
7        S208     NaN   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Name']=df['Name'].fillna('Ramesh')
df

/tmp/ipykernel_5088/4111258573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name']=df['Name'].fillna('Ramesh')

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21       M    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    NaN   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Course']=df['Course'].fillna('BCA')
df

/tmp/ipykernel_5088/3662916238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Course']=df['Course'].fillna('BCA')

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21       M    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA    NaN  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Marks']=df['Marks'].fillna(100)
df

/tmp/ipykernel_5088/3030847996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marks']=df['Marks'].fillna(100)

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21       M    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0        NaN     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['City']=df['City'].fillna('Tumakur')
df

/tmp/ipykernel_5088/2295848641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City']=df['City'].fillna('Tumakur')

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20       M    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19       F    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21       M    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19       F    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Gender']=df['Gender'].replace({"F":"Female","M":"Male"})
df

/tmp/ipykernel_5088/3182450881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=df['Gender'].replace({"F":"Female","M":"Male"})

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6         NaN    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Student ID']=df['Student ID'].fillna('S207')
df

/tmp/ipykernel_5088/547453194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Student ID']=df['Student ID'].fillna('S207')

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S212   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S213  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S214   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S215  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Student ID']=df['Student ID'].replace({"S212":"S211","S213":"S212","S214":"S213","S215":"S214"})
df

/tmp/ipykernel_5088/3596741129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Student ID']=df['Student ID'].replace({"S212":"S211","S213":"S212","S214":"S213","S215":"S214"})

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  -19  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S211   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S212  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S213   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S214  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
import numpy as np
df.loc[df['Age']<10,'Age']=np.nan
df

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya  20.0  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  20.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6        S207    Ravi  21.0    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju   NaN  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
11       S211   Divya  21.0  Female    BCA   76.0     Mysuru     18-07-2023
12       S212  Naveen  22.0    Male    BCA  100.0  Hyderabad     25-08-2023
13       S213   Pooja  20.0  Female    BBA   68.0    Tumakur     12-07-2023
14       S214  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Age']=df['Age'].fillna(22)
df

/tmp/ipykernel_5088/2448365174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].fillna(22)

   Student ID    Name   Age  Gender Course  Marks       City Admission Date
0        S201   Rahul  20.0    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya  20.0  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun  21.0    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha  19.0  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran  20.0    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali  22.0  Female    BCA  -45.0    Chennai     15-07-2023
6        S207    Ravi  21.0    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh  20.0  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju  22.0  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh  22.0    Male    MCA   89.0    Chennai     05-08-2023
11       S211   Divya  21.0  Female    BCA   76.0     Mysuru     18-07-2023
12       S212  Naveen  22.0    Male    BCA  100.0  Hyderabad     25-08-2023
13       S213   Pooja  20.0  Female    BBA   68.0    Tumakur     12-07-2023
14       S214  Mahesh  23.0    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Age']=df['Age'].astype(int)
df

/tmp/ipykernel_5088/71083683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].astype(int)

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  -45.0    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju   22  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S211   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S212  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S213   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S214  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df.dtypes

Student ID         object
Name               object
Age                 int64
Gender             object
Course             object
Marks             float64
City               object
Admission Date     object
dtype: object

In [ ]:
import numpy as np
df.loc[df['Marks']<10,'Marks']=np.nan
df

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    NaN    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju   22  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S211   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S212  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S213   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S214  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Marks']=df['Marks'].fillna(120)
df

/tmp/ipykernel_5088/1475576721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marks']=df['Marks'].fillna(120)

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA   85.0  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA   78.0    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA   92.0  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA   88.0     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA   65.0  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA  120.0    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA   95.0      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA   72.0  Hyderabad     22-08-2023
8        S209   Manju   22  Female    BBA   80.0  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA   89.0    Chennai     05-08-2023
11       S211   Divya   21  Female    BCA   76.0     Mysuru     18-07-2023
12       S212  Naveen   22    Male    BCA  100.0  Hyderabad     25-08-2023
13       S213   Pooja   20  Female    BBA   68.0    Tumakur     12-07-2023
14       S214  Mahesh   23    Male    MCA  105.0  Bengaluru     30-06-2023

In [ ]:
df['Marks']=df['Marks'].astype(int)
df

/tmp/ipykernel_5088/721663445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marks']=df['Marks'].astype(int)

   Student ID    Name  Age  Gender Course  Marks       City Admission Date
0        S201   Rahul   20    Male    BCA     85  Bengaluru     12-06-2023
1        S202   Priya   20  Female    BBA     78    Chennai     15-07-2023
2        S203   Arjun   21    Male    BCA     92  Hyderabad     10-08-2023
3        S204   Sneha   19  Female    MCA     88     Mysuru     20-06-2023
4        S205   Kiran   20    Male    BBA     65  Bengaluru     10-07-2023
5        S206  Anjali   22  Female    BCA    120    Chennai     15-07-2023
6        S207    Ravi   21    Male    MCA     95      Delhi     01-08-2023
7        S208  Ramesh   20  Female    BCA     72  Hyderabad     22-08-2023
8        S209   Manju   22  Female    BBA     80  Bengaluru     10-07-2023
9        S210  Suresh   22    Male    MCA     89    Chennai     05-08-2023
11       S211   Divya   21  Female    BCA     76     Mysuru     18-07-2023
12       S212  Naveen   22    Male    BCA    100  Hyderabad     25-08-2023
13       S213   Pooja   20  Female    BBA     68    Tumakur     12-07-2023
14       S214  Mahesh   23    Male    MCA    105  Bengaluru     30-06-2023

In [ ]:
df.shape

(14, 8)

In [ ]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City',
       'Admission Date'],
      dtype='object')

In [ ]:
df['Marks'].min()

65

In [ ]:
df['Marks'].max()

120

In [ ]:
df['Marks'].sum()

np.int64(1213)

In [ ]:
df["Marks"].mean()

np.float64(86.64285714285714)

In [ ]:
df['Age'].sum()

np.int64(293)

In [ ]:
df['Age'].mean()

np.float64(20.928571428571427)

In [ ]:

df['Age'].min()

19

In [ ]:
df['Age'].max()

23

In [ ]:
c=df.drop("Admission Date",axis=1)
c

   Student ID    Name  Age  Gender Course  Marks       City
0        S201   Rahul   20    Male    BCA     85  Bengaluru
1        S202   Priya   20  Female    BBA     78    Chennai
2        S203   Arjun   21    Male    BCA     92  Hyderabad
3        S204   Sneha   19  Female    MCA     88     Mysuru
4        S205   Kiran   20    Male    BBA     65  Bengaluru
5        S206  Anjali   22  Female    BCA    120    Chennai
6        S207    Ravi   21    Male    MCA     95      Delhi
7        S208  Ramesh   20  Female    BCA     72  Hyderabad
8        S209   Manju   22  Female    BBA     80  Bengaluru
9        S210  Suresh   22    Male    MCA     89    Chennai
11       S211   Divya   21  Female    BCA     76     Mysuru
12       S212  Naveen   22    Male    BCA    100  Hyderabad
13       S213   Pooja   20  Female    BBA     68    Tumakur
14       S214  Mahesh   23    Male    MCA    105  Bengaluru

In [ ]:
c.shape

(14, 7)

In [ ]:
c['Marks']=c['Marks'].replace({""})

/tmp/ipykernel_5088/1770397698.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  c['Marks']=c['Marks'].replace({""})

In [ ]:
c['Marks']=c['Marks'].replace({120:70,105:67})
c

   Student ID    Name  Age  Gender Course  Marks       City
0        S201   Rahul   20    Male    BCA     85  Bengaluru
1        S202   Priya   20  Female    BBA     78    Chennai
2        S203   Arjun   21    Male    BCA     92  Hyderabad
3        S204   Sneha   19  Female    MCA     88     Mysuru
4        S205   Kiran   20    Male    BBA     65  Bengaluru
5        S206  Anjali   22  Female    BCA     70    Chennai
6        S207    Ravi   21    Male    MCA     95      Delhi
7        S208  Ramesh   20  Female    BCA     72  Hyderabad
8        S209   Manju   22  Female    BBA     80  Bengaluru
9        S210  Suresh   22    Male    MCA     89    Chennai
11       S211   Divya   21  Female    BCA     76     Mysuru
12       S212  Naveen   22    Male    BCA    100  Hyderabad
13       S213   Pooja   20  Female    BBA     68    Tumakur
14       S214  Mahesh   23    Male    MCA     67  Bengaluru

In [ ]:
c.max()

Student ID       S214
Name           Suresh
Age                23
Gender           Male
Course            MCA
Marks             100
City          Tumakur
dtype: object

In [ ]:
c.min()

Student ID         S201
Name             Anjali
Age                  19
Gender           Female
Course              BBA
Marks                65
City          Bengaluru
dtype: object

In [ ]:
c["Marks"].max()

100

In [ ]:
c["Marks"].min()

65

In [ ]:
c["Marks"].sum()

np.int64(1125)

In [ ]:
c["Marks"].mean()

np.float64(80.35714285714286)

In [ ]:
c.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City'], dtype='object')

In [ ]:
c.shape

(14, 7)

In [ ]:
c

   Student ID    Name  Age  Gender Course  Marks       City
0        S201   Rahul   20    Male    BCA     85  Bengaluru
1        S202   Priya   20  Female    BBA     78    Chennai
2        S203   Arjun   21    Male    BCA     92  Hyderabad
3        S204   Sneha   19  Female    MCA     88     Mysuru
4        S205   Kiran   20    Male    BBA     65  Bengaluru
5        S206  Anjali   22  Female    BCA     70    Chennai
6        S207    Ravi   21    Male    MCA     95      Delhi
7        S208  Ramesh   20  Female    BCA     72  Hyderabad
8        S209   Manju   22  Female    BBA     80  Bengaluru
9        S210  Suresh   22    Male    MCA     89    Chennai
11       S211   Divya   21  Female    BCA     76     Mysuru
12       S212  Naveen   22    Male    BCA    100  Hyderabad
13       S213   Pooja   20  Female    BBA     68    Tumakur
14       S214  Mahesh   23    Male    MCA     67  Bengaluru

In [ ]:
c.dtypes

Student ID    object
Name          object
Age            int64
Gender        object
Course        object
Marks          int64
City          object
dtype: object

In [ ]:
print(c['Course'].value_counts())

Course
BCA    6
BBA    4
MCA    4
Name: count, dtype: int64

In [ ]:
print(c['Course'].unique())

['BCA' 'BBA' 'MCA']

In [ ]:
c.describe()

             Age       Marks
count  14.000000   14.000000
mean   20.928571   80.357143
std     1.141139   11.297428
min    19.000000   65.000000
25%    20.000000   70.500000
50%    21.000000   79.000000
75%    22.000000   88.750000
max    23.000000  100.000000

Exploratory Data Analysis(EDA)- Is the process of exploring,understanding,cleaning,and analyzing data before creating visualization or mechine learning models.


> **The Standard Industry EDA pipeline**



1. Load
2. Understand


1. Types

1. Missing

1. Duplicates
2. Outliers


2. Relationship


2. Visualizations

1. Insights

**Mapping the Evidence:Types of Data**


>***Data types***


1. Numerical Data(Numbers for math operations)


*  Continuous(Decimals allowed)
*  Discrete(whole numbers only)


2. Categorical Data


*   Nominal(No inherent order)
*   Ordinal(Meaningful order)

**Data Formats:How Evidence is Stored**


1.  Structured Data(strictly organized in rows)
2.  Semi-structured Data(partially organized,uses tags or keys)


1.  Unstructured Data(does not follow rows/columns formats)

****The Core Engine of AI****


> Machine Learning is a branch of AI that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed for every individual situation.

**Applications of Machine Learning**


1.  Navigations(Traffic prediction)
2.  Emails(spam email detection)

1.  Social Media(Friend and content recommendation)
2.  Education(student performance prediction)

1.   Healthcare(disease prediction)
2.   Banking(fraud detection)

1.   Shopping(product recommendation)

**The 3 Primary Paradigms of Algorithmic Learning**


1.   Supervised Learning

1.   Unsupervised Learning
2.   Reinforment Learning