In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
pd.__version__

'2.2.3'

pandas is a built on top of numpy
2 main Data strctures
1.series(1 coloum)
2.Dataframe(table)



Series:It is a one-dimensional labeled array.think of it as one single coloum in an excel sheet.

In [ ]:
#series
import pandas as pd
kiran=pd.Series([1,2,3,4,5])
kiran

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import pandas as pd
marks=pd.Series([85,90,75,95])
marks

0    85
1    90
2    75
3    95
dtype: int64

Note:pandas automatically assigns an index to every values.

In [ ]:
#numpy
import pandas as pd
arr=pd.array([10,20,30,40])
s=pd.Series(arr)
print(s)

0    10
1    20
2    30
3    40
dtype: Int64

In [ ]:
#tuple
import pandas as pd
arr=pd.array((10,20,30,40))
s=pd.Series(arr)
print(s)

0    10
1    20
2    30
3    40
dtype: Int64

In [ ]:
#dictionary
import pandas as pd
student={'Rahul':67,
         'Anita':92,
         'jhon':79}
s=pd.Series(student)
print(s)

Rahul    67
Anita    92
jhon     79
dtype: int64

In [ ]:
#list
arr=pd.array([10,20,30,40])
s=pd.Series(arr)
print(s)

0    10
1    20
2    30
3    40
dtype: Int64

In [ ]:
import pandas as pd
marks={'sakshi':67,
         'shravya':92,
         'sursti':79}
s=pd.Series(student)
print(marks['sakshi'])

67

In [ ]:
#slicing
import pandas as pd
marks=pd.Series([85,90,75,95,80,82,29,93,23])
print(marks[1:6])

1    90
2    75
3    95
4    80
5    82
dtype: int64

In [ ]:
import pandas as pd
student={'Name':"keerti",
         'Reg_no':193,
         'place':"gadag",
         'college':"kle college",
         'year':2027,
         'Result':"pass"}
s=pd.Series(student)
print(s)
print(student)
print(s[5])
print(s[2])
print(s['Name'])
print(s['college'])
print(s[-2])

Name            keerti
Reg_no             193
place            gadag
college    kle college
year              2027
Result            pass
dtype: object
{'Name': 'keerti', 'Reg_no': 193, 'place': 'gadag', 'college': 'kle college', 'year': 2027, 'Result': 'pass'}
pass
gadag
keerti
kle college
2027

/tmp/ipykernel_976/694395939.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[5])
/tmp/ipykernel_976/694395939.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])
/tmp/ipykernel_976/694395939.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[-2])

In [ ]:
import pandas as pd
arr=[76,45,64,74,73,44,41]
a=pd.Series(arr)
a
print(a[a>73])

0    76
3    74
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
arr=np.array([29,93,23])
arr+=5
arr
new=pd.Series(arr)
print(new)
print(new*2)
print(new.size)
print(new.shape)
print(new.values)
print(new[new>29])
print(new.dtype)
print(new.index)

0    34
1    98
2    28
dtype: int64
0     68
1    196
2     56
dtype: int64
3
(3,)
[34 98 28]
0    34
1    98
dtype: int64
int64
RangeIndex(start=0, stop=3, step=1)

DataFrame:A two-dimensional labeled array it look like excel sheet it contain rows and coloums.

---


   **Ingesting data into a DataFrame**       

---





1.   Dictionary
2.   List of Dicts

1.   .csv File
2.   .xlsx File

In [ ]:
#1.dict to dataframe
import pandas as pd
demo={
    'Reg No':[11,12,13,14,15,16],
    'Name':['sushila','keerti','sangeeta','anusha','ramesh','kiran'],
    'Age':[67,18,100,98,98,32],
    'place':['sortur','hubli','betageri','koppla','belatti','betageri']
}
data=pd.DataFrame(demo)
data

   Reg No      Name  Age     place
0      11   sushila   67    sortur
1      12    keerti   18     hubli
2      13  sangeeta  100  betageri
3      14    anusha   98    koppla
4      15    ramesh   98   belatti
5      16     kiran   32  betageri

In [ ]:
#2.csv file to ndataframe
import pandas as pd
data=pd.read_csv("/content/Employee.csv")
data

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

In [ ]:
import pandas as pd
data=pd.read_excel("/content/employee.xlsx")
data

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

Note-Read_csv and Read_excel automatically parse headers & align data into rows and colums instantly

In [ ]:
import pandas as pd
data=pd.read_excel("/content/employee.xlsx")
data

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

In [ ]:
print(data['Name'])

0     Aditya
1      Sagar
2    prajwal
3     Rajesh
Name: Name, dtype: object

In [ ]:
print(data['Emp_id'])

0    1
1    2
2    3
3    4
Name: Emp_id, dtype: int64

In [ ]:
data['Salary']

0    20000000
1     3000000
2      400000
3     5000000
Name: Salary, dtype: int64

In [ ]:
data['Company']

0       google
1    microsoft
2          TCS
3        Wipro
Name: Company, dtype: object

In [ ]:
#2.csv file to ndataframe
import pandas as pd
data=pd.read_csv("/content/Employee.csv")
data

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

In [ ]:
print(data['Name'])

0     Aditya
1      Sagar
2    prajwal
3     Rajesh
Name: Name, dtype: object

In [ ]:
print(data[['Name','Salary']])

      Name    Salary
0   Aditya  20000000
1    Sagar   3000000
2  prajwal    400000
3   Rajesh   5000000

In [ ]:
data['Age']=[25,
             30,
             28,
             18]
data.to_csv('Age',index=False)
data

   Emp_id     Name    Salary    Company  Age
0       1   Aditya  20000000     google   25
1       2    Sagar   3000000  microsoft   30
2       3  prajwal    400000        TCS   28
3       4   Rajesh   5000000      Wipro   18

In [ ]:
data['city']=['Bengaluru',
            'Hydrabad',
            'mysore',
            'Dharwad']
data.to_csv('city',index=False)
data

   Emp_id     Name    Salary    Company  Age       city
0       1   Aditya  20000000     google   25  Bengaluru
1       2    Sagar   3000000  microsoft   30   Hydrabad
2       3  prajwal    400000        TCS   28     mysore
3       4   Rajesh   5000000      Wipro   18    Dharwad

In [ ]:
data=data.drop('city',axis=1)
data

   Emp_id     Name    Salary    Company  Age
0       1   Aditya  20000000     google   25
1       2    Sagar   3000000  microsoft   30
2       3  prajwal    400000        TCS   28
3       4   Rajesh   5000000      Wipro   18

In [ ]:
data= data.drop('Age',axis=1)
data

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

what do these arguments mean?

>what is axis=1?


>*axis=0 means look at the rows.


> *axis=1 means look at the columns.


>what is inplace=True?




>*without this,pandas just show you preview of the deleted column.inplace=True saves the changes permanentely to you variable.

In [ ]:
data.columns

Index(['Emp_id', 'Name', 'Salary', 'Company'], dtype='object')

In [ ]:
data.shape

(4, 4)

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data.dtypes

Emp_id      int64
Name       object
Salary      int64
Company    object
dtype: object

In [ ]:
data.head()

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

In [ ]:
data.tail()

   Emp_id     Name    Salary    Company
0       1   Aditya  20000000     google
1       2    Sagar   3000000  microsoft
2       3  prajwal    400000        TCS
3       4   Rajesh   5000000      Wipro

In [ ]:
data.describe()

         Emp_id        Salary
count  4.000000  4.000000e+00
mean   2.500000  7.100000e+06
std    1.290994  8.803787e+06
min    1.000000  4.000000e+05
25%    1.750000  2.350000e+06
50%    2.500000  4.000000e+06
75%    3.250000  8.750000e+06
max    4.000000  2.000000e+07

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Emp_id   4 non-null      int64
 1   Name     4 non-null      object
 2   Salary   4 non-null      int64
 3   Company  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

The **Explorer** Tool kit


1.   .head()

1.   .tail()
2.   .describe()


2.   .info()

In [ ]:
import pandas as pd
employee={
    'ID':[101,102,103,104],
    'Name':['Rahul','Rakesh','jhon','kiran'],
    'department':['IT','HR','sales','Finance'],
    'salary':[100000,200000,300000,400000]
}
df=pd.DataFrame(employee)
print(df)

    ID    Name department  salary
0  101   Rahul         IT  100000
1  102  Rakesh         HR  200000
2  103    jhon      sales  300000
3  104   kiran    Finance  400000

In [ ]:
print(df['salary'].mean())

250000.0

In [ ]:
print(df[df['department']=='IT'])

    ID   Name department  salary
0  101  Rahul         IT  100000

In [ ]:
import pandas as pd
data=pd.read_excel("/content/employeeinfo.xlsx")
data

,Employee Id,Name,Age,Gender,Department,Salary,City,joining-date
0,E101,akash,25.0,M,IT,45000,Begaluru,12-01-2023
1,E102,Megha,NaN,F,HR,38000,Chennai,15-02-2022
2,E103,jhon,28.0,Male,finance,55000,NaN,10-05-2023
3,NaN,Kavya,240.0,female,IT,48000,Mysuru,20-03-2023
4,E105,darshini,26.0,Male,Sales,25000,Begaluru,10-06-2026
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,15-02-2022
6,E107,darshini,26.0,male,sales,25000,Begaluru,10-06-2021
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,01-02-2023
8,E109,NaN,-27.0,female,Finance,52000,Hydrabad,22-08-2022
9,E110,Vikas,22.0,Male,IT,999999,Chennai,05-01-2024